// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: comment.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getComments = `-- name: GetComments :many
SELECT id, post_id, author_id, platform, created_at, updated_at, body
FROM comments where id = $1
`

func (q *Queries) GetComments(ctx context.Context, id uuid.UUID) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getComments, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
