// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: post.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getPostById = `-- name: GetPostById :one
SELECT id, title, image_url, image_reference, created_at, updated_at, description, "source", tags
FROM public.posts
WHERE ID = $1
`

type GetPostByIdRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	ImageUrl       sql.NullString `json:"image_url"`
	ImageReference sql.NullString `json:"image_reference"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	Description    sql.NullString `json:"description"`
	Source         sql.NullString `json:"source"`
	Tags           []string       `json:"tags"`
}

func (q *Queries) GetPostById(ctx context.Context, id uuid.UUID) (GetPostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i GetPostByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ImageUrl,
		&i.ImageReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Source,
		pq.Array(&i.Tags),
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, title, image_url, image_reference, created_at, description, updated_at, "source", tags
FROM public.posts order by created_at desc
`

type GetPostsRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	ImageUrl       sql.NullString `json:"image_url"`
	ImageReference sql.NullString `json:"image_reference"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	Description    sql.NullString `json:"description"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	Source         sql.NullString `json:"source"`
	Tags           []string       `json:"tags"`
}

func (q *Queries) GetPosts(ctx context.Context) ([]GetPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageUrl,
			&i.ImageReference,
			&i.CreatedAt,
			&i.Description,
			&i.UpdatedAt,
			&i.Source,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
