// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetComments(ctx context.Context, id uuid.UUID) ([]Comment, error)
	GetPostById(ctx context.Context, id uuid.UUID) (Post, error)
	GetPosts(ctx context.Context) ([]Post, error)
}

var _ Querier = (*Queries)(nil)
