development:
  dialect: postgres
  database: blog
  user: root
  password: root
  host: 127.0.0.1
  pool: 5

test:
  url:
    { { envOr "TEST_DATABASE_URL" "postgres://root:root@127.0.0.1:5432/blog" } }

production:
  url: { { envOr "DATABASE_URL" "postgres://root:root@127.0.0.1:5432/blog" } }
